login:
    path: /
    defaults: { _controller: ModeloBundle:Login:inicio }
    
login_check:
    path: /login_check
    
logout:
    path: /logout

modelo_homepage:
    path:     /dashboard
    defaults: { _controller: ModeloBundle:Default:index }
    
socio_add:    
    path:     /socio/add
    defaults: { _controller: ModeloBundle:Socio:addSocio }

socios:    
    path:     /socio
    defaults: { _controller: ModeloBundle:Socio:index }

socios_search:    
    path:     /socio/search
    defaults: { _controller: ModeloBundle:Socio:search }

socio_detail:
    path:     /socio/detalle/{id}
    defaults: { _controller: ModeloBundle:Socio:detailSocio }
   
socio_delete:
    path:     /socio/delete/{id}
    defaults: { _controller: ModeloBundle:Socio:deleteSocio }
    
socio_update:
    path:     /socio/update/{id}
    defaults: { _controller: ModeloBundle:Socio:updateSocio }
    
asociados:    
    path:     /asociado
    defaults: { _controller: ModeloBundle:Asociado:index }

asociado_add:    
    path:     /asociado/add
    defaults: { _controller: ModeloBundle:Asociado:addAsociado }

asociado_update:
    path:     /asociado/update/{id}
    defaults: { _controller: ModeloBundle:Asociado:updateAsociado } 
    
asociado_delete:
    path:     /asociado/delete/{id}
    defaults: { _controller: ModeloBundle:Asociado:deleteAsociado }

asociado_detail:
    path:     /asociado/detalle/{id}
    defaults: { _controller: ModeloBundle:Asociado:detailAsociado }
    
fichas:    
    path:     /ficha/list/{page}
    defaults: { _controller: ModeloBundle:Ficha:index, page:1 }

ficha_add:    
    path:     /ficha/add
    defaults: { _controller: ModeloBundle:Ficha:addFicha }

ficha_update:
    path:     /ficha/update/{id}
    defaults: { _controller: ModeloBundle:Ficha:updateFicha } 
    
ficha_delete:
    path:     /ficha/delete/{id}
    defaults: { _controller: ModeloBundle:Ficha:deleteFicha }
    
    
disciplinas:    
    path:     /disciplina/list
    defaults: { _controller: ModeloBundle:Disciplina:index}

disciplina_add:    
    path:     /disciplina/add
    defaults: { _controller: ModeloBundle:Disciplina:addDisciplina }

disciplina_update:
    path:     /disciplina/update/{id}
    defaults: { _controller: ModeloBundle:Disciplina:updateDisciplina } 
    
disciplina_delete:
    path:     /disciplina/delete/{id}
    defaults: { _controller: ModeloBundle:Disciplina:deleteDisciplina }
   
campeonatos:    
    path:     /campeonato/list
    defaults: { _controller: ModeloBundle:Campeonato:index}

campeonato_add:    
    path:     /campeonato/add
    defaults: { _controller: ModeloBundle:Campeonato:addCampeonato }

campeonato_update:
    path:     /campeonato/update/{id}
    defaults: { _controller: ModeloBundle:Campeonato:updateCampeonato } 
    
campeonato_delete:
    path:     /campeonato/delete/{id}
    defaults: { _controller: ModeloBundle:Campeonato:deleteCampeonato }
    
campeonato_detail:
    path:     /campeonato/detalle/{id}
    defaults: { _controller: ModeloBundle:Campeonato:detailCampeonato }
    
equipos:    
    path:     /equipo/list
    defaults: { _controller: ModeloBundle:Equipo:index}

equipo_add:    
    path:     /equipo/add
    defaults: { _controller: ModeloBundle:Equipo:addEquipo }

equipo_update:
    path:     /equipo/update/{id}
    defaults: { _controller: ModeloBundle:Equipo:updateEquipo } 
    
equipo_delete:
    path:     /equipo/delete/{id}
    defaults: { _controller: ModeloBundle:Equipo:deleteEquipo }
    
equipo_detail:
    path:     /equipo/detalle/{id}
    defaults: { _controller: ModeloBundle:Equipo:detailEquipo }