login:
    path: /
    defaults: { _controller: ModeloBundle:Login:inicio }
    
login_check:
    path: /login_check
    
logout:
    path: /logout

modelo_homepage:
    path:     /dashboard
    defaults: { _controller: ModeloBundle:Default:index }

email_test:
    path:     /email-test
    defaults: { _controller: ModeloBundle:Usuario:emailTest }
    methods: [POST]

app_card:
    resource: "@ModeloBundle/Resources/config/routing/card.yml"
    prefix: /card

app_usuario:
    resource: "@ModeloBundle/Resources/config/routing/usuario.yml"
    prefix: /usuario
    
app_asociado:
    resource: "@ModeloBundle/Resources/config/routing/asociado.yml"
    prefix: /asociado
    
app_socio:
    resource: "@ModeloBundle/Resources/config/routing/socio.yml"
    prefix: /socio    
    
app_fichas:
    resource: "@ModeloBundle/Resources/config/routing/fichas.yml"
    prefix: /fichas   
    
app_disciplinas:
    resource: "@ModeloBundle/Resources/config/routing/disciplinas.yml"
    prefix: /disciplinas   

app_campeonato:
    resource: "@ModeloBundle/Resources/config/routing/campeonato.yml"
    prefix: /campeonato  

app_equipo:
    resource: "@ModeloBundle/Resources/config/routing/equipo.yml"
    prefix: /equipo       

app_empleado:
    resource: "@ModeloBundle/Resources/config/routing/empleado.yml"
    prefix: /empleado     

app_departamento:
    resource: "@ModeloBundle/Resources/config/routing/departamento.yml"
    prefix: /departamento      
    
app_cargo:
    resource: "@ModeloBundle/Resources/config/routing/cargo.yml"
    prefix: /cargo
    
app_familiar:
    resource: "@ModeloBundle/Resources/config/routing/familiar.yml"
    prefix: /familiar
    
app_registro:
    resource: "@ModeloBundle/Resources/config/routing/registro.yml"
    prefix: /seguridad     
 