fichas:    
    path:     /list/{page}
    defaults: { _controller: ModeloBundle:Ficha:index, page:1 }

ficha_add:    
    path:     /add
    defaults: { _controller: ModeloBundle:Ficha:addFicha }

ficha_update:
    path:     /update/{id}
    defaults: { _controller: ModeloBundle:Ficha:updateFicha } 
    
ficha_delete:
    path:     /delete/{id}
    defaults: { _controller: ModeloBundle:Ficha:deleteFicha }