ModeloBundle\Entity\Asociado:
    type: entity
    table: asociado
    repositoryClass: ModeloBundle\Repository\AsociadoRepository
    indexes:
        TSocios_idSocio:
            columns:
                - idSocio
    uniqueConstraints:
        cedula:
            columns:
                - cedula
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador Asociado'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Nombres Asociado'
        apellidos:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Apellido Asociado'
        cedula:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                comment: 'Cedula identidad asociado'
        fecha:
            type: date
            nullable: false
            options:
                comment: 'Fecha registro Asociado'
        numasociado:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                comment: 'Numero Asociado'
        codigo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Codigo asociado'
        solvente:
            type: boolean
            nullable: false
            options:
                comment: 'Campo Logico de Solvencia'
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                comment: 'Ruta de Imagen'
    manyToOne:
        idsocio:
            targetEntity: Socio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idSocio:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
