ModeloBundle\Entity\Empleado:
    type: entity
    table: empleado
    repositoryClass: ModeloBundle\Repository\EmpleadoRepository
    indexes:
        TDepartamento_idDepartamento:
            columns:
                - idDepartamento
                - idCargo
        idCargo:
            columns:
                - idCargo
        IDX_D9D9BF521E7A331A:
            columns:
                - idDepartamento
    uniqueConstraints:
        cedula:
            columns:
                - cedula
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador empleado'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Nombres empleado'
        apellidos:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Apellido Empleado'
        cedula:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Cedula Empleado'
        edad:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Edad Empleado'
        nacimiento:
            type: date
            nullable: false
            options:
                comment: 'Fecha nacimiento'
        registro:
            type: date
            nullable: false
            options:
                comment: 'Fecha registro'
        actualizacion:
            type: date
            nullable: true
            options:
                comment: 'fecha actualizacion'
        emision:
            type: date
            nullable: true
            options:
                comment: 'fecha emision'
        vencimiento:
            type: date
            nullable: true
            options:
                comment: 'fecha vencimiento'
        estado:
            type: boolean
            nullable: false
            options:
                comment: 'Estado Empleado'
        codigo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Codigo Carnet Empleado'
        old:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                comment: 'Codigo carnet anterior'
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                comment: 'Ruta imagen'
    manyToOne:
        iddepartamento:
            targetEntity: Departamento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idDepartamento:
                    referencedColumnName: id
            orphanRemoval: false
        idcargo:
            targetEntity: Cargo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCargo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
