ModeloBundle\Entity\Jugador:
    type: entity
    table: jugador
    uniqueConstraints:
        cedula:
            columns:
                - cedula
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador Jugador'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Nombres jugador'
        apellidos:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Apellidos Jugador'
        cedula:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                comment: 'Cedula Identidad Jugador'
        edad:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Edad jugador'
        nacimiento:
            type: date
            nullable: false
            options:
                comment: 'Fecha Nacimiento'
        registro:
            type: date
            nullable: false
            options:
                comment: 'Fecha registro'
        actualizacion:
            type: date
            nullable: true
            options:
                comment: 'Fecha Ultima Actualizacion'
        emision:
            type: date
            nullable: true
            options:
                comment: 'Fecha emisión carnet'
        vencimiento:
            type: date
            nullable: true
            options:
                comment: 'Fecha vencimiento carnet'
        codigo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                comment: 'Codigo Carnet afiliado'
        numafiliacion:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
                comment: 'numero de afiliacion'
        solvente:
            type: boolean
            nullable: true
            options:
                comment: solvencia
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                comment: 'ruta imagen'
    lifecycleCallbacks: {  }
