ModeloBundle\Entity\Tipofamiliar:
    type: entity
    table: tipofamiliar
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador tipo Asociados'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'nombre tipo de asociado'
        descripcion:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'descripcion tipo de asociado'
    lifecycleCallbacks: {  }
